// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PendingDevice {
    "device_id": string;
    "name": string;

    /** Creates a new PendingDevice instance. */
    constructor($$source: Partial<PendingDevice> = {}) {
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingDevice($$parsedSource as Partial<PendingDevice>);
    }
}
