// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Menu {

    /** Creates a new Menu instance. */
    constructor($$source: Partial<Menu> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Menu instance from a string or object.
     */
    static createFrom($$source: any = {}): Menu {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Menu($$parsedSource as Partial<Menu>);
    }
}

export class MenuItem {

    /** Creates a new MenuItem instance. */
    constructor($$source: Partial<MenuItem> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MenuItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MenuItem($$parsedSource as Partial<MenuItem>);
    }
}
