// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveredDevice is a device discovered via mDNS.
 */
export interface DiscoveredDevice {
    "DeviceID": string;
    "Name": string;
    "IP": string;
    "Port": number;
}
