// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiscoveredDevice is a device discovered via mDNS.
 */
export class DiscoveredDevice {
    /**
     * Creates a new DiscoveredDevice instance.
     * @param {Partial<DiscoveredDevice>} [$$source = {}] - The source object to create the DiscoveredDevice.
     */
    constructor($$source = {}) {
        if (!("DeviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DeviceID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("IP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IP"] = "";
        }
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoveredDevice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveredDevice(/** @type {Partial<DiscoveredDevice>} */($$parsedSource));
    }
}
