// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiscoveredDevice is a device discovered via mDNS.
 */
export class DiscoveredDevice {
    "DeviceID": string;
    "Name": string;
    "IP": string;
    "Port": number;

    /** Creates a new DiscoveredDevice instance. */
    constructor($$source: Partial<DiscoveredDevice> = {}) {
        if (!("DeviceID" in $$source)) {
            this["DeviceID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IP" in $$source)) {
            this["IP"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveredDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveredDevice($$parsedSource as Partial<DiscoveredDevice>);
    }
}
