// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadProgress tracks the current model download state.
 */
export class DownloadProgress {
    /**
     * Creates a new DownloadProgress instance.
     * @param {Partial<DownloadProgress>} [$$source = {}] - The source object to create the DownloadProgress.
     */
    constructor($$source = {}) {
        if (!("downloading" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["downloading"] = false;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("downloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downloaded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DownloadProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadProgress(/** @type {Partial<DownloadProgress>} */($$parsedSource));
    }
}
