// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DownloadProgress tracks the current model download state.
 */
export class DownloadProgress {
    "downloading": boolean;
    "total": number;
    "downloaded": number;

    /** Creates a new DownloadProgress instance. */
    constructor($$source: Partial<DownloadProgress> = {}) {
        if (!("downloading" in $$source)) {
            this["downloading"] = false;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadProgress($$parsedSource as Partial<DownloadProgress>);
    }
}
