// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress tracks the current model download state.
 */
export interface DownloadProgress {
    "downloading": boolean;
    "total": number;
    "downloaded": number;
}
