// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Agent {
    /**
     * Creates a new Agent instance.
     * @param {Partial<Agent>} [$$source = {}] - The source object to create the Agent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["selected"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["version"] = null;
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["config"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Agent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Agent(/** @type {Partial<Agent>} */($$parsedSource));
    }
}

export class AuthorizedDevice {
    /**
     * Creates a new AuthorizedDevice instance.
     * @param {Partial<AuthorizedDevice>} [$$source = {}] - The source object to create the AuthorizedDevice.
     */
    constructor($$source = {}) {
        if (!("device_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("authorized_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorized_at"] = "";
        }
        if (!("last_seen_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen_ip"] = "";
        }
        if (!("last_seen_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen_at"] = "";
        }
        if (!("revoked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["revoked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthorizedDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthorizedDevice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthorizedDevice(/** @type {Partial<AuthorizedDevice>} */($$parsedSource));
    }
}

export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("audio_url" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["audio_url"] = null;
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["summary"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("device_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device_id"] = "";
        }
        if (!("agent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_id"] = "";
        }
        if (!("acp_session_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["acp_session_id"] = null;
        }
        if (!("acp_agent_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["acp_agent_id"] = null;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("closed_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["closed_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}
