// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Agent {
    "id": string;
    "name": string;
    "command": string;
    "enabled": boolean;
    "selected": boolean;
    "version": string | null;
    "config": string | null;
    "installed": boolean;
    "install_command": string | null;

    /** Creates a new Agent instance. */
    constructor($$source: Partial<Agent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("selected" in $$source)) {
            this["selected"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = null;
        }
        if (!("config" in $$source)) {
            this["config"] = null;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("install_command" in $$source)) {
            this["install_command"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     */
    static createFrom($$source: any = {}): Agent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Agent($$parsedSource as Partial<Agent>);
    }
}

export class AuthorizedDevice {
    "device_id": string;
    "name": string;
    "alias": string;
    "authorized_at": string;
    "last_seen_ip": string;
    "last_seen_at": string;
    "revoked": boolean;

    /** Creates a new AuthorizedDevice instance. */
    constructor($$source: Partial<AuthorizedDevice> = {}) {
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("alias" in $$source)) {
            this["alias"] = "";
        }
        if (!("authorized_at" in $$source)) {
            this["authorized_at"] = "";
        }
        if (!("last_seen_ip" in $$source)) {
            this["last_seen_ip"] = "";
        }
        if (!("last_seen_at" in $$source)) {
            this["last_seen_at"] = "";
        }
        if (!("revoked" in $$source)) {
            this["revoked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthorizedDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthorizedDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthorizedDevice($$parsedSource as Partial<AuthorizedDevice>);
    }
}

export class Message {
    "id": string;
    "session_id": string;
    "role": string;
    "content": string;
    "audio_url": string | null;
    "summary": string | null;
    "created_at": string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("audio_url" in $$source)) {
            this["audio_url"] = null;
        }
        if (!("summary" in $$source)) {
            this["summary"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class Session {
    "id": string;
    "device_id": string;
    "agent_id": string;
    "acp_session_id": string | null;
    "acp_agent_id": string | null;
    "created_at": string;
    "closed_at": string | null;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("device_id" in $$source)) {
            this["device_id"] = "";
        }
        if (!("agent_id" in $$source)) {
            this["agent_id"] = "";
        }
        if (!("acp_session_id" in $$source)) {
            this["acp_session_id"] = null;
        }
        if (!("acp_agent_id" in $$source)) {
            this["acp_agent_id"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("closed_at" in $$source)) {
            this["closed_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}
