// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Agent {
    "id": string;
    "name": string;
    "command": string;
    "enabled": boolean;
    "selected": boolean;
    "version": string | null;
    "config": string | null;
}

export interface AuthorizedDevice {
    "device_id": string;
    "name": string;
    "alias": string;
    "authorized_at": string;
    "last_seen_ip": string;
    "last_seen_at": string;
    "revoked": boolean;
}

export interface Message {
    "id": string;
    "session_id": string;
    "role": string;
    "content": string;
    "audio_url": string | null;
    "summary": string | null;
    "created_at": string;
}

export interface Session {
    "id": string;
    "device_id": string;
    "agent_id": string;
    "acp_session_id": string | null;
    "acp_agent_id": string | null;
    "created_at": string;
    "closed_at": string | null;
}
