// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "./internal/discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as firmware$0 from "./internal/firmware/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "./internal/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as speech$0 from "./internal/speech/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * AuthorizeDevice is called from the frontend when user approves a device.
 * @param {string} deviceID
 * @returns {$CancellablePromise<void>}
 */
export function AuthorizeDevice(deviceID) {
    return $Call.ByID(1837634914, deviceID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelFlash() {
    return $Call.ByID(3536286619);
}

/**
 * ConnectToDevice notifies a scanned device to open a WebSocket back to the desktop.
 * The device is NOT authorized here; authorization happens after the device sends
 * a valid hello and the user approves it via AuthorizePendingDevice. This prevents
 * the auto-reconnect loop from repeatedly notifying the device while the first
 * handshake is still in progress.
 * @param {string} deviceIP
 * @param {number} devicePort
 * @param {string} deviceID
 * @param {string} deviceName
 * @returns {$CancellablePromise<void>}
 */
export function ConnectToDevice(deviceIP, devicePort, deviceID, deviceName) {
    return $Call.ByID(1376679050, deviceIP, devicePort, deviceID, deviceName);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function CurrentFirmwareVersion() {
    return $Call.ByID(4024534077);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function FindEsptool() {
    return $Call.ByID(1191879424);
}

/**
 * @param {string} port
 * @returns {$CancellablePromise<void>}
 */
export function FlashFirmware(port) {
    return $Call.ByID(1445842456, port);
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<string>}
 */
export function GetDeviceAlias(deviceID) {
    return $Call.ByID(1475520567, deviceID);
}

/**
 * @returns {$CancellablePromise<firmware$0.FlashProgress>}
 */
export function GetFlashProgress() {
    return $Call.ByID(2233710848).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSTTDownloadProgress exposes the local whisper model download progress.
 * @returns {$CancellablePromise<speech$0.DownloadProgress>}
 */
export function GetSTTDownloadProgress() {
    return $Call.ByID(2507448111).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<store$0.Message[]>}
 */
export function GetSessionMessages(sessionID) {
    return $Call.ByID(988970873, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function HasEmbeddedFirmware() {
    return $Call.ByID(3682150640);
}

/**
 * @returns {$CancellablePromise<store$0.Agent[]>}
 */
export function ListAgents() {
    return $Call.ByID(578673379).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<store$0.AuthorizedDevice[]>}
 */
export function ListAuthorizedDevices() {
    return $Call.ByID(1577096867).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListConnectedDeviceIDs() {
    return $Call.ByID(1131397920).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Message[]>}
 */
export function ListMessages(limit, offset) {
    return $Call.ByID(2939394281, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<gateway$0.PendingDevice[]>}
 */
export function ListPendingDevices() {
    return $Call.ByID(4263251995).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<firmware$0.SerialPortInfo[]>}
 */
export function ListSerialPorts() {
    return $Call.ByID(3298629127).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Session[]>}
 */
export function ListSessions(limit, offset) {
    return $Call.ByID(827108744, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ReadDeviceFirmwareVersion listens on the given serial port for the device's
 * startup banner and returns the firmware version reported by the device.
 * @param {string} port
 * @returns {$CancellablePromise<string>}
 */
export function ReadDeviceFirmwareVersion(port) {
    return $Call.ByID(225378278, port);
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<void>}
 */
export function RevokeDevice(deviceID) {
    return $Call.ByID(2622980785, deviceID);
}

/**
 * STTReady exposes the STT initialization status to the frontend.
 * @returns {$CancellablePromise<boolean>}
 */
export function STTReady() {
    return $Call.ByID(664123937);
}

/**
 * @returns {$CancellablePromise<discovery$0.DiscoveredDevice[]>}
 */
export function ScanDevices() {
    return $Call.ByID(752654171).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.Message[]>}
 */
export function SearchMessages(query, limit) {
    return $Call.ByID(3203246577, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SelectAgent marks the chosen agent as selected and clears selection from all others.
 * @param {string} agentID
 * @returns {$CancellablePromise<void>}
 */
export function SelectAgent(agentID) {
    return $Call.ByID(1605882214, agentID);
}

/**
 * @param {string} deviceID
 * @param {string} alias
 * @returns {$CancellablePromise<void>}
 */
export function SetDeviceAlias(deviceID, alias) {
    return $Call.ByID(4066166771, deviceID, alias);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSetting(key, value) {
    return $Call.ByID(4214292049, key, value);
}

/**
 * @param {application$0.Menu | null} menu
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayAgentMenu(menu) {
    return $Call.ByID(2881811, menu);
}

/**
 * @param {application$0.MenuItem | null} item
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayDeviceItem(item) {
    return $Call.ByID(3133036894, item);
}

/**
 * @param {application$0.MenuItem | null} item
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayOpenItem(item) {
    return $Call.ByID(2312067580, item);
}

/**
 * @param {application$0.MenuItem | null} item
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayQuitItem(item) {
    return $Call.ByID(3681134623, item);
}

/**
 * @param {store$0.Agent} agent
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAgent(agent) {
    return $Call.ByID(1405986229, agent);
}

// Private type creation functions
const $$createType0 = firmware$0.FlashProgress.createFrom;
const $$createType1 = speech$0.DownloadProgress.createFrom;
const $$createType2 = store$0.Message.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = store$0.Agent.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = store$0.AuthorizedDevice.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = gateway$0.PendingDevice.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = firmware$0.SerialPortInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = store$0.Session.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = discovery$0.DiscoveredDevice.createFrom;
const $$createType17 = $Create.Array($$createType16);
