// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "./internal/discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "./internal/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * AuthorizeDevice is called from the frontend when user approves a device.
 */
export function AuthorizeDevice(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(1837634914, deviceID);
}

/**
 * ConnectToDevice notifies a scanned device to open a WebSocket back to the desktop.
 * The device is NOT authorized here; authorization happens after the device sends
 * a valid hello and the user approves it via AuthorizePendingDevice. This prevents
 * the auto-reconnect loop from repeatedly notifying the device while the first
 * handshake is still in progress.
 */
export function ConnectToDevice(deviceIP: string, devicePort: number, deviceID: string, deviceName: string): $CancellablePromise<void> {
    return $Call.ByID(1376679050, deviceIP, devicePort, deviceID, deviceName);
}

export function GetSessionMessages(sessionID: string): $CancellablePromise<store$0.Message[] | null> {
    return $Call.ByID(988970873, sessionID);
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2554697378);
}

export function ListAgents(): $CancellablePromise<store$0.Agent[] | null> {
    return $Call.ByID(578673379);
}

export function ListAuthorizedDevices(): $CancellablePromise<store$0.AuthorizedDevice[] | null> {
    return $Call.ByID(1577096867);
}

export function ListPendingDevices(): $CancellablePromise<gateway$0.PendingDevice[] | null> {
    return $Call.ByID(4263251995);
}

export function ListSessions(limit: number, offset: number): $CancellablePromise<store$0.Session[] | null> {
    return $Call.ByID(827108744, limit, offset);
}

export function RevokeDevice(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(2622980785, deviceID);
}

export function ScanDevices(): $CancellablePromise<discovery$0.DiscoveredDevice[] | null> {
    return $Call.ByID(752654171);
}

/**
 * SelectAgent enables only the chosen agent and disables all others.
 */
export function SelectAgent(agentID: string): $CancellablePromise<void> {
    return $Call.ByID(1605882214, agentID);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4214292049, key, value);
}

export function SetTrayAgentMenu(menu: application$0.Menu | null): $CancellablePromise<void> {
    return $Call.ByID(2881811, menu);
}

export function SetTrayDeviceItem(item: application$0.MenuItem | null): $CancellablePromise<void> {
    return $Call.ByID(3133036894, item);
}

export function UpdateAgent(agent: store$0.Agent): $CancellablePromise<void> {
    return $Call.ByID(1405986229, agent);
}
