// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "./internal/discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as firmware$0 from "./internal/firmware/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "./internal/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as speech$0 from "./internal/speech/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * AuthorizeDevice is called from the frontend when user approves a device.
 */
export function AuthorizeDevice(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(1837634914, deviceID);
}

export function CancelFlash(): $CancellablePromise<void> {
    return $Call.ByID(3536286619);
}

export function CancelOTAUpdate(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(1473713506, deviceID);
}

export function CheckDeviceFirmwareVersion(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(3237672752, deviceID);
}

/**
 * ConnectToDevice notifies a scanned device to open a WebSocket back to the desktop.
 * The device is NOT authorized here; authorization happens after the device sends
 * a valid hello and the user approves it via AuthorizePendingDevice. This prevents
 * the auto-reconnect loop from repeatedly notifying the device while the first
 * handshake is still in progress.
 */
export function ConnectToDevice(deviceIP: string, devicePort: number, deviceID: string, deviceName: string): $CancellablePromise<void> {
    return $Call.ByID(1376679050, deviceIP, devicePort, deviceID, deviceName);
}

export function CurrentFirmwareVersion(): $CancellablePromise<string> {
    return $Call.ByID(4024534077);
}

export function FindEsptool(): $CancellablePromise<string> {
    return $Call.ByID(1191879424);
}

export function FlashFirmware(port: string): $CancellablePromise<void> {
    return $Call.ByID(1445842456, port);
}

export function GetDeviceAlias(deviceID: string): $CancellablePromise<string> {
    return $Call.ByID(1475520567, deviceID);
}

export function GetDeviceFirmwareVersion(deviceID: string): $CancellablePromise<string> {
    return $Call.ByID(72830496, deviceID);
}

export function GetFlashProgress(): $CancellablePromise<firmware$0.FlashProgress> {
    return $Call.ByID(2233710848).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetOTAProgress(deviceID: string): $CancellablePromise<firmware$0.OTAProgress> {
    return $Call.ByID(3461899768, deviceID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSTTDownloadProgress exposes the local whisper model download progress.
 */
export function GetSTTDownloadProgress(): $CancellablePromise<speech$0.DownloadProgress> {
    return $Call.ByID(2507448111).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetSessionMessages(sessionID: string): $CancellablePromise<store$0.Message[]> {
    return $Call.ByID(988970873, sessionID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType5($result);
    });
}

export function HasEmbeddedFirmware(): $CancellablePromise<boolean> {
    return $Call.ByID(3682150640);
}

export function ListAgents(): $CancellablePromise<store$0.Agent[]> {
    return $Call.ByID(578673379).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListAuthorizedDevices(): $CancellablePromise<store$0.AuthorizedDevice[]> {
    return $Call.ByID(1577096867).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListConnectedDeviceIDs(): $CancellablePromise<string[]> {
    return $Call.ByID(1131397920).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListMessages(limit: number, offset: number): $CancellablePromise<store$0.Message[]> {
    return $Call.ByID(2939394281, limit, offset).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListPendingDevices(): $CancellablePromise<gateway$0.PendingDevice[]> {
    return $Call.ByID(4263251995).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListSerialPorts(): $CancellablePromise<firmware$0.SerialPortInfo[]> {
    return $Call.ByID(3298629127).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListSessions(limit: number, offset: number): $CancellablePromise<store$0.Session[]> {
    return $Call.ByID(827108744, limit, offset).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ReadDeviceFirmwareVersion listens on the given serial port for the device's
 * startup banner and returns the firmware version reported by the device.
 */
export function ReadDeviceFirmwareVersion(port: string): $CancellablePromise<string> {
    return $Call.ByID(225378278, port);
}

export function RevokeDevice(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(2622980785, deviceID);
}

/**
 * STTReady exposes the STT initialization status to the frontend.
 */
export function STTReady(): $CancellablePromise<boolean> {
    return $Call.ByID(664123937);
}

export function ScanDevices(): $CancellablePromise<discovery$0.DiscoveredDevice[]> {
    return $Call.ByID(752654171).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SearchMessages(query: string, limit: number): $CancellablePromise<store$0.Message[]> {
    return $Call.ByID(3203246577, query, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SelectAgent marks the chosen agent as selected and clears selection from all others.
 */
export function SelectAgent(agentID: string): $CancellablePromise<void> {
    return $Call.ByID(1605882214, agentID);
}

export function SetDeviceAlias(deviceID: string, alias: string): $CancellablePromise<void> {
    return $Call.ByID(4066166771, deviceID, alias);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4214292049, key, value);
}

export function SetTrayAgentMenu(menu: application$0.Menu | null): $CancellablePromise<void> {
    return $Call.ByID(2881811, menu);
}

export function SetTrayDeviceItem(item: application$0.MenuItem | null): $CancellablePromise<void> {
    return $Call.ByID(3133036894, item);
}

export function SetTrayOpenItem(item: application$0.MenuItem | null): $CancellablePromise<void> {
    return $Call.ByID(2312067580, item);
}

export function SetTrayQuitItem(item: application$0.MenuItem | null): $CancellablePromise<void> {
    return $Call.ByID(3681134623, item);
}

export function StartOTAUpdate(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(665326238, deviceID);
}

export function UpdateAgent(agent: store$0.Agent): $CancellablePromise<void> {
    return $Call.ByID(1405986229, agent);
}

// Private type creation functions
const $$createType0 = firmware$0.FlashProgress.createFrom;
const $$createType1 = firmware$0.OTAProgress.createFrom;
const $$createType2 = speech$0.DownloadProgress.createFrom;
const $$createType3 = store$0.Message.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = store$0.Agent.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = store$0.AuthorizedDevice.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = gateway$0.PendingDevice.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = firmware$0.SerialPortInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = store$0.Session.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = discovery$0.DiscoveredDevice.createFrom;
const $$createType18 = $Create.Array($$createType17);
