// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FlashProgress is the public progress snapshot exposed to the frontend.
 */
export class FlashProgress {
    /**
     * Creates a new FlashProgress instance.
     * @param {Partial<FlashProgress>} [$$source = {}] - The source object to create the FlashProgress.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {FlashStage}
             */
            this["stage"] = FlashStage.$zero;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlashProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashProgress(/** @type {Partial<FlashProgress>} */($$parsedSource));
    }
}

/**
 * FlashStage represents the current phase of a firmware flash operation.
 * @readonly
 * @enum {string}
 */
export const FlashStage = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StageIdle: "idle",
    StageDetecting: "detecting",
    StageErasing: "erasing",
    StageWriting: "writing",
    StageVerifying: "verifying",
    StageDone: "done",
    StageCancelled: "cancelled",
    StageError: "error",
};

/**
 * SerialPortInfo describes a candidate USB/serial port for flashing.
 */
export class SerialPortInfo {
    /**
     * Creates a new SerialPortInfo instance.
     * @param {Partial<SerialPortInfo>} [$$source = {}] - The source object to create the SerialPortInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SerialPortInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortInfo(/** @type {Partial<SerialPortInfo>} */($$parsedSource));
    }
}
