// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlashProgress is the public progress snapshot exposed to the frontend.
 */
export interface FlashProgress {
    "running": boolean;
    "stage": FlashStage;
    "percent": number;
    "message": string;
    "error": string;
}

/**
 * FlashStage represents the current phase of a firmware flash operation.
 */
export enum FlashStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StageIdle = "idle",
    StageDetecting = "detecting",
    StageErasing = "erasing",
    StageWriting = "writing",
    StageVerifying = "verifying",
    StageDone = "done",
    StageCancelled = "cancelled",
    StageError = "error",
};

/**
 * OTAProgress is the public progress snapshot for a wireless firmware update.
 */
export interface OTAProgress {
    "running": boolean;
    "stage": string;
    "percent": number;
    "message": string;
    "error": string;
    "device_version": string;
}

/**
 * SerialPortInfo describes a candidate USB/serial port for flashing.
 */
export interface SerialPortInfo {
    "path": string;
    "name": string;
}
