// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FlashProgress is the public progress snapshot exposed to the frontend.
 */
export class FlashProgress {
    "running": boolean;
    "stage": FlashStage;
    "percent": number;
    "message": string;
    "error": string;

    /** Creates a new FlashProgress instance. */
    constructor($$source: Partial<FlashProgress> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("stage" in $$source)) {
            this["stage"] = FlashStage.$zero;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): FlashProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashProgress($$parsedSource as Partial<FlashProgress>);
    }
}

/**
 * FlashStage represents the current phase of a firmware flash operation.
 */
export enum FlashStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StageIdle = "idle",
    StageDetecting = "detecting",
    StageErasing = "erasing",
    StageWriting = "writing",
    StageVerifying = "verifying",
    StageDone = "done",
    StageCancelled = "cancelled",
    StageError = "error",
};

/**
 * OTAProgress is the public progress snapshot for a wireless firmware update.
 */
export class OTAProgress {
    "running": boolean;
    "stage": string;
    "percent": number;
    "message": string;
    "error": string;
    "device_version": string;

    /** Creates a new OTAProgress instance. */
    constructor($$source: Partial<OTAProgress> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("device_version" in $$source)) {
            this["device_version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OTAProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): OTAProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OTAProgress($$parsedSource as Partial<OTAProgress>);
    }
}

/**
 * SerialPortInfo describes a candidate USB/serial port for flashing.
 */
export class SerialPortInfo {
    "path": string;
    "name": string;

    /** Creates a new SerialPortInfo instance. */
    constructor($$source: Partial<SerialPortInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SerialPortInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortInfo($$parsedSource as Partial<SerialPortInfo>);
    }
}
