[env:m5stickc-s3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    m5stack/M5Unified
    gilmaimon/ArduinoWebsockets
    bblanchon/ArduinoJson

build_flags =
    -DCORE_DEBUG_LEVEL=4
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DARDUINO_M5STACK_CORES3
