[platformio]
default_envs = m5stickc-s3

[env:m5stickc-s3]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi

lib_deps =
    m5stack/M5Unified @ ^0.2.7
    links2004/WebSockets
    bblanchon/ArduinoJson

build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=4
    '-DFIRMWARE_VERSION="876fe77"'
